config/routes.rb
Rails.application.routes.draw do
  root 'students#index'

 resources :students do
    collection do
      post :confirm
    end 
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
      if params[:back]
        render :new
      else
        if @student.save
          redirect_to students_path, notice: "Elève enregistré !"
        else 
          render :new 
        end
      end
  end

  def show
    
  end

  def destroy
    
    @student.destroy
    redirect_to students_path, notice: "Elève supprimé"
  end

  def update
    @student.update(student_params)
    if @student.update(student_params)
      redirect_to students_path, notice: "Informations sur l'élève  modifiés !"
    else 
      render :edit  
    end
  end

  def edit
  end

  def confirm 
    @student = Student.new(student_params)
    render :new if @student.invalid?
  end
  
  private
  def student_params 
    params.require(:student).permit(:last_name, :first_name, :age)
  end
  
  def set_student 
    @student = Student.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_students_path
        elsif action_name == 'edit'
            student_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_form.html.erb
<%= form_with(model: @student, local: true, url: choose_new_or_edit) do |form| %>

  <div class="blog_title">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <div class="blog_content">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <div class="blog_content">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Retour à l'acceuil ", students_path%>

app/views/students/confirm.html.erb
<h3> Envoyer avec le contenu suivant ?</h3>

<%= form_with(model: @student, url: students_path(@student), local: true) do |form| %>
  <%= form.hidden_field :last_name %>
  <%= form.hidden_field :first_name %>
  <%= form.hidden_field :age %>
  <p>Last Name : <%= @student.last_name %></p>
  <p>First Name : <%= @student.first_name %></p>
  <p>Age : <%= @student.age %></p>
  <%= form.submit  "L'enregistrer" %>
  <%= form.submit  "Retour", name: 'back'%>
<% end %>

app/views/students/edit.html.erb
<h1>Modifier Enregistrements</h1>

<%= render '/partials/form' %>

app/views/students/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Acceuil</a>
      
      <a class="d-flex" href="#">Ajouter un élève</a>
      </div>
    </div>
  </nav>



<%= notice %>
<div class="row">
    <div class="col-3">

    </div>
    <div class="col-6">
        <h1 class="text-center">Students List</h1> <br>
        <table class="table table-striped table-hover">
            <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Age</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        
            <% @students.each do |student|%>
        
                <tr>
                    <td> <%= student.last_name %> </td>
                    <td> <%= student.first_name %> </td>
                    <td> <%= student.age %> </td>
                    <td> <%= link_to 'Show', student_path(student.id) %> </td>
                    <td> <%= link_to 'Edit', edit_student_path(student.id) %> </td>
                    <td> <%= link_to 'Delete', student_path(student.id), method: :delete ,
                    data: {confirm: 'Êtes-vous sûr de vouloir supprimer ?'}%> </td>
                </tr>
        
            <% end %>
        </table>
        <%= link_to 'Ajouter un eleve', new_student_path%>
    </div>
    <div class="col-3"></div>
   

app/views/students/new.html.erb
<h1>Ajouter un eleve</h1>


<%= render '/partials/form' %>

app/views/students/show.html.erb
<h1 class="text-center">Info</h1>

<div class="row">
    <div class="col-3"></div>
    <div class="col">
        <table class="table table-striped">

            <tr>
                <th>Last Name : </th>
                <td> <%= @student.last_name %> </td>
            </tr>
        
            <tr>
                <th>First Name : </th>
                <td> <%= @student.first_name %> </td>
            </tr>
        
            <tr>
                <th>Age : </th>
                <td> <%= @student.age %> </td>
            </tr>
        </table>
        <%= link_to 'Back', students_path%>
    </div>
    <div class="col-3"></div>
</div>